version: '3.8'
services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: tool_rental_db
      POSTGRES_USER: tool_rental_user
      POSTGRES_PASSWORD: strongpassword
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn tool_rental.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://tool_rental_user:strongpassword@db:5432/tool_rental_db

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A tool_rental worker -l info
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://tool_rental_user:strongpassword@db:5432/tool_rental_db
      - CELERY_BROKER_URL=redis://redis:6379/0

volumes:
  postgres_data: